---
- name: minikubes-with-contour
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    minikube_profile_name: my-demo

  roles:
    - role: kameshsampath.minikube
    - role: kameshsampath.k8s_app_spices
