# the demo work directory
work_dir: "{{ playbook_dir }}/work"
# the kubeconfig directory
kubeconfig_dir: "{{ work_dir }}/.kube"
# the kubernetes version to use with minikube
minikube_kubernetes_version: v1.21.6
# the minikube home directory
minikube_home_dir: "{{ work_dir }}/.minikube"
# the helm.sh version to use
helm_version: 3.7.1
# the kubectl version
kubectl_version: 1.21.6

# minikube Kubernetes Clusters
minikube_profiles:
#  mgmt:
#    create: yes
#    destroy: no
#    addons:
#      - metallb
#    lbStartIP: 192.168.64.80
#    lbEndIP: 192.168.64.90
  cluster1:
    create: yes
    destroy: no
    addons:
      - metallb
    lbStartIP: 192.168.64.100
    lbEndIP: 192.168.64.110

# Istio Clusters
istio_clusters:
  cluster1:
    version: 1.12.1
    install: yes
    k8s_context: cluster1
