namespace: kameshsampath
name: kubernetes_spices
version: 0.2.1
readme: README.md
authors:
  - Kamesh Sampath <kamesh.sampath@hotmail.com>
description: Spice your Kubernetes clusters with extra addtional components
license_file: "LICENSE"
tags:
  - knative
  - tektoncd
  - gitea
  - argocd
dependencies:
  ansible.posix: '>=1.2.0'
  community.general: '>=1.2.0'
  kubernetes.core: '>=2.2.0'
  community.aws: ">=1.4.0"
  community.docker: ">=1.7.0"
repository: https://github.com/kameshsampath/ansible-collection-kubernetes_spices
documentation: https://kameshsampath.github.io/ansible-collection-kubernetes-spices/
homepage: https://github.com/kameshsampath/ansible-collection-kubernetes_spices
issues: https://github.com/kameshsampath/ansible-collection-kubernetes_spices
build_ignore:
  - ".cache"
  - ".idea"
  - ".vscode"
  - ".project"
  - ".classpath"
  - ".factorypath"
  - "documentation"
  - ".kube"
  - ".venv"
  - ".settings"
  - ".github"
  - "**/*.pem"
  - "**/temp.json"
  - "*.tar.gz"
  - "work"
  - "hack"
  - "collections"
  - "filter/my_test.py"
  - "gh-pages"
  - "node_modules"
  - "supplemental-ui"
  - "lib"
  - "builder-ee"
  - "gh-pages"
  - "FILES.json"
  - "dev-site.yml"
  - "site.yml"
  - "Vagrantfile"
  - "Makefile"
  - "site.sh"
  - "yarn*"
  - "package.json"
  - "playbook.yml"
  - "ansible.cfg"
  - "gulpfile*"
  - "poetry*"
  - "pyproject.toml"
  - ".ansible-lint"
  - ".editorconfig"
  - ".gitignore"
  - ".gitpod.Dockerfile"
  - ".gitpod.yml"
  - ".tool-versions"
  - ".yamllint"
