---
roles:
  - name: geerlingguy.docker
    version: ">=3.1.2"
  - name: geerlingguy.pip
    version: ">=2.1.0"
collections:
  - name: ansible.posix
    version: ">1.2.0"
  - name: community.aws
    version: ">=1.4.0"
  - name: community.kubernetes
    version: ">=1.2.1"
  - name: community.general
    version: ">=3.2.0"
  - name: community.docker
    version: ">1.7.0"
