---
- name: Converge
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   minikube_profile: molecule
   deploy_ingress: False

  roles:
    - role: kameshsampath.minikube
