---
- name: Verify
  hosts: localhost
  connection: local

  collections:
    - community.kubernetes

  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   minikube_profile_name: molecule


- name: Destroy test resources
  import_playbook: destroy.yml
