---
- name: Converge
  hosts: localhost
  connection: local

  collections:
  - community.kubernetes

  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   minikube_profile_name: molecule-knative
   deploy_knative: True

  roles:
    - role: kameshsampath.minikube
