---
- name: "Istio Kube Context"
  debug:
    var: kubernetes_spices_istio_k8s_context

- name: "Fail if the Istio kube context is not defined"
  fail:
    msg: "Istio Kube Context is not defined, please set the variable 'kubernetes_spices_istio_k8s_context' to kubernetes context where you wish to have Gitea installed "
  when: kubernetes_spices_istio_k8s_context is not defined 

- name: "Fail when version istio info does not exist"
  fail:
    msg: "Istio Version not available"
  when: kubernetes_spices_istio_version is not defined 

- name: "Set Istio Revision Fact"
  set_fact:
    kubernetes_spices_istio_revision: "{{ kubernetes_spices_istio_version | kameshsampath.kubernetes_spices.version_to_revision }}"

- name: "Istio Version"
  debug: 
    var: kubernetes_spices_istio_version

- name: "Istio Revision"
  debug: 
    var: kubernetes_spices_istio_revision

- name: "Set Istio Revision Work Directory"
  set_fact:
    kubernetes_spices_istio_revision_work_dir: "{{ work_dir }}/{{ kubernetes_spices_istio_revision }}"

- name: "Generate Istio Control Plane Deployment"
  ansible.builtin.template:
    src: operator/istiod.yaml.j2
    dest: "{{ kubernetes_spices_istio_revision_work_dir }}/control-plane.yaml"
  register: kubernetes_spices_controlpane_manifest_file
  when: kubernetes_spices_controlpane_manifest is not defined 
    
- name: "Set Control Plane Manifest"
  set_fact:
    kubernetes_spices_controlpane_manifest: "{{ kubernetes_spices_istio_revision_work_dir }}/control-plane.yaml"
  when: kubernetes_spices_controlpane_manifest is not defined 

- name: "Generate Istio Gateway Deployment"
  ansible.builtin.template:
    src: operator/istio-gateway.yaml.j2
    dest: "{{ kubernetes_spices_istio_revision_work_dir }}/ingress-gateway.yaml"
  register: kubernetes_spices_gateways_manifest_file
  when:  kubernetes_spices_gateways_manifest is not defined

- name: "Set Istio Gateways Manifest"
  set_fact:
    kubernetes_spices_gateways_manifest: "{{ kubernetes_spices_istio_revision_work_dir + '/ingress-gateway.yaml' }}"
  when:  kubernetes_spices_gateways_manifest is not defined

- name: "Undeploy Istio Ingress Gateway"
  kubernetes.core.k8s:
    state: absent
    src: "{{ kubernetes_spices_gateways_manifest }}"
    context: "{{ kubernetes_spices_istio_k8s_context }}"
    wait: yes

- name: "Undeploy Istio Control Plane"
  kubernetes.core.k8s:
    state: absent
    src: "{{ kubernetes_spices_controlpane_manifest }}"
    context: "{{ kubernetes_spices_istio_k8s_context }}"
    wait: yes

- name: "Uninstall Istio Operator"
  kubernetes.core.k8s:
    state: absent
    src: "{{ kubernetes_spices_istio_revision_work_dir }}/operator.yaml"
    namespace: "{{ kubernetes_spices_istio_operator_namespace }}"
    context: "{{ kubernetes_spices_istio_k8s_context }}"
    wait: yes

- name: "Delete Istio Namespaces"
  kubernetes.core.k8s:
    state: absent
    kind: Namespace
    name: "{{ kube_istio_ns_item }}"
    wait: yes
  loop:
    - "{{ kubernetes_spices_istio_operator_namespace }}"
    - "{{ kubernetes_spices_istio_namespace }}"
    - "{{ kubernetes_spices_istio_gateways_namespace }}"
  loop_control:
     loop_var: kube_istio_ns_item


