---
roles:
  - name: kameshsampath.kind
    src: https://github.com/kameshsampath/ansible-role-kind
  - name: kameshsampath.minikube
    src: https://github.com/kameshsampath/ansible-role-minikube

collections:
  - name: kubernetes.core
    version: 0.11.1
