# Docker
docker_repo_url: https://download.docker.com/linux
docker_yum_repo_url: "{{ docker_repo_url }}/{{ (ansible_distribution == 'Fedora') | ternary('fedora','centos') }}/docker-{{ docker_edition }}.repo"
docker_yum_repo_enable_nightly: '0'
docker_yum_repo_enable_test: '0'
docker_yum_gpg_key: "{{ docker_repo_url }}/centos/gpg"
docker_edition: 'ce'
docker_package: "docker-{{ docker_edition }}"

k9s_version: v0.24.10