---
# This runs only for clusters that are built and run locally
# e.g. KinD
- name: "Local Cloud"
  hosts: kind
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    kind_create: true
    cluster_name: gloo-edge-demo
  roles:
    - name: kameshsampath.kubernetes_spices.kind
# Applies stack to all the cloud
- name: "Gloo Edge Community"
  hosts: spices
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ## Gloo Edge Configuration
    ####
    # Gloo Edge Setup
    deploy_gloo_edge: true #<.>
    # Enable/disable discovery true/false
    gloo_discovery_enabled: false #<.>
    # Namespace to install Gloo into
    gloo_write_namespace: my-gloo #<.>
    # Gloo Watch Namespaces
    gloo_watch_namespaces: #<.>
      - demo-1-8-6
      - demo-1-10-2
      - my-gloo
    # Use NodePorts for Gloo Proxy http/https true/false
    gloo_proxy_nodeport: true #<.>

  roles:
    - kameshsampath.kubernetes_spices.k8s_app_spices
