---
- name: Converge
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    kind_create: false #<.>
  roles:
    - role: kameshsampath.kubernetes_spices.kind
