---
- name: "Knative Defaults"
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core

  vars:
    # to ensure we are on python3
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    # Default versions are v0.23.0, you can override it using knative_serving_version, knative_eventing_version
    deploy_knative: True #<.>
    
  roles:
    - role: kameshsampath.kind
    - role: kameshsampath.k8s_app_spices
