---
- name: "Ensure work dir set"
  set_fact:
    work_dir: "{{ work_dir | default(playbook_dir) }}"

- name: "Ensure bin dir is set"
  set_fact:
    bin_dir: "{{ bin_dir | default( work_dir + '/bin' ) }}"

- name: "Ensure {{ bin_dir}}"
  ansible.builtin.file:
     state: directory
     path: "{{ bin_dir }}"

- name: "Download gitea (macOS)"
  ansible.builtin.get_url:
    url: "https://dl.gitea.io/gitea/{{ kubernetes_spices_gitea_cli_version }}/gitea-{{ kubernetes_spices_gitea_cli_version }}-darwin-10.12-amd64"
    checksum: "sha256:https://dl.gitea.io/gitea/{{ kubernetes_spices_gitea_cli_version }}/gitea-{{ kubernetes_spices_gitea_cli_version }}-darwin-10.12-amd64.sha256"
    dest: "{{ bin_dir }}/gitea"
    mode: "0755"
    timeout: 30
  when: ansible_os_family == 'Darwin'

- name: "Download gitea (linux)"
  ansible.builtin.get_url:
    url: "https://dl.gitea.io/gitea/{{ kubernetes_spices_gitea_cli_version }}/gitea-{{ kubernetes_spices_gitea_cli_version }}-linux-amd64"
    checksum: "sha256:https://dl.gitea.io/gitea/{{ kubernetes_spices_gitea_cli_version }}/gitea-{{ kubernetes_spices_gitea_cli_version }}-linux-amd64.sha256"
    dest: "{{ bin_dir }}/gitea"
    mode: "0755"
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Debian'

- name: "Gitea Kube Context"
  debug:
    var: kubernetes_spices_gitea_k8s_context

- name: "Fail if the Gitea kube context is not defined"
  fail:
    msg: "Gitea Kube Context is not defined, please set the variable 'kubernetes_spices_gitea_k8s_context' to kubernetes context where you wish to have Gitea installed "
  when: kubernetes_spices_gitea_k8s_context is not defined 

- name: "Add Gloo Edge Community Repo"
  kubernetes.core.helm_repository:
    name: gloo
    repo_url: "https://storage.googleapis.com/solo-public-helm"

- name: "Refresh helm repositories"
  ansible.builtin.command:
    argv:
      - helm
      - repo
      - update

- name: "Query Gloo Versions"
  ansible.builtin.command:
    argv:
      - helm
      - search 
      - repo
      - gloo/gloo
      - -ojson
  register: gloo_version_info
  changed_when: false
  when: kubernetes_spices_gitea_gloo_version is not defined

- name: "Fail when version gloo info does not exist"
  fail:
    msg: "Gloo Version not available"
  when: kubernetes_spices_gitea_gloo_version is not defined and gloo_version_info.stdout is not defined

- name: "Set Gloo Version"
  set_fact:
    kubernetes_spices_gitea_gloo_version: "{{ gloo_version_info.stdout  | from_json | first | community.general.json_query('version') }}"
  when: kubernetes_spices_gitea_gloo_version is not defined

- name: "Gitea Gloo Version"
  debug: 
    var: kubernetes_spices_gitea_gloo_version

- name: "Deploy Gloo"
  kubernetes.core.helm:
    release_name: gloo
    chart_ref: gloo/gloo
    release_namespace: "{{ kubernetes_spices_gitea_namespace}}"
    create_namespace: yes
    chart_version: "{{ kubernetes_spices_gitea_gloo_version }}"
    values:
      discovery:
        enabled: false
        fdsMode: DISABLED
      settings:
        writeNamespace: "{{ kubernetes_spices_gitea_namespace  }}"
        watchNamespace: "{{ kubernetes_spices_gitea_namespace  }}"
    update_repo_cache: yes
    context: "{{ kubernetes_spices_gitea_k8s_context }}"
    wait: yes

- name: "Create Gitea Deployment namespace {{ kubernetes_spices_gitea_namespace }}"
  kubernetes.core.k8s:
    kind: Namespace
    name: "{{ kubernetes_spices_gitea_namespace }}"
    state: present

- name: "Create gitea admin user"
  set_fact:
    gitea_admin_user:
      username: 'gitea'
      # "{{ lookup('password', work_dir + '/gitea.password chars=ascii_letters,digits,punctuation') }}"
      password: "password"
      email: 'gitea@example.com'

# - debug:
#     var: gitea_admin_user
#   tags:
#     - gitea

- name: "Add Gitea Helm Repo"
  kubernetes.core.helm_repository:
    name: gitea-charts
    repo_url: "https://dl.gitea.io/charts/"

- name: "Query Gitea Versions"
  ansible.builtin.command:
    argv:
      - helm
      - search 
      - repo
      - gitea-charts/gitea
      - -ojson
  register: gitea_version_info
  changed_when: false
  when: gitea_version is not defined

- name: "Fail when version Gitea info does not exist"
  fail:
    msg: "Gitea Version not available"
  when: gitea_version is not defined and gitea_version_info.stdout is not defined

- name: Set Gitea Facts
  set_fact:
    gitea_version: "{{ gitea_version_info.stdout  | from_json | first | community.general.json_query('version') }}"
  when: gitea_version is not defined
  vars:
    q: "status.loadBalancer.ingress[*].ip"

- name: "Gitea Version"
  debug: 
    var: gitea_version

- name: "Generate Gitea config"
  ansible.builtin.template:
    src: "gitea-values.yaml.j2"
    dest: "{{ work_dir }}/gitea-values.yaml"

- name: "Deploy Gitea"
  kubernetes.core.helm:
    release_name: gitea
    chart_ref: gitea-charts/gitea
    release_namespace: "{{ kubernetes_spices_gitea_namespace }}"
    create_namespace: yes
    chart_version: "{{ gitea_version }}"
    values_files:
        - "{{ work_dir }}/gitea-values.yaml"
    update_repo_cache: yes
    context: "{{ kubernetes_spices_gitea_k8s_context }}"
    wait: yes
