---
# Cluster details
kubernetes_cluster_type: kind

# ASDF
asdf_version: v0.8.1

# Helm
helm_version: "3.6.2"

# Operator Lifecycle Manager 
deploy_olm: false
olm_version: "v0.18.2"
olm_namespace: olm

# Gloo Edge
deploy_gloo_edge: false
gloo_edge_edition: ce
gloo_edge_version: "1.8.0"
gloo_write_namespace: gloo-system
gloo_proxy_nodeport: false
gloo_discovery_enabled: true
gloo_watch_namespaces: []
gloo_install_override_files: []
  
# Istio
deploy_istio: false
istio_versions: 
  - "1.10.2"
istio_namespace: istio-system
deploy_istio_gateway: false

# Keycloak
deploy_keycloak: false
keycloak_namespace: keycloak
keycloak_admin_user: admin
keycloak_admin_password: admin

#Knative
deploy_knative: false
knative_version: v0.23.0
knative_eventing_version: v0.23.0
knative_serving_version: v0.23.0
registries_skip_tag_resolving:
  - example.com
  - example.org
  - test.com
  - test.org
  - ko.local
  - dev.local
  - localhost:5000
  - kind-registry.local:5000

#Postgresql
deploy_postgresql: false
postgresql_namespace: db

#Tektoncd
deploy_tektoncd: false
tektoncd_pipelines_version: v0.25.0
tektoncd_triggers_version: v0.14.2
