---
- name: Destroy 'molecule-ingress' test resources
  hosts: localhost
  connection: local

  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   minikube_profile_name: molecule-ingress
   deploy_ingress: True

  roles:
    - role: kameshsampath.minikube
