---
- name: "Gloo Edge Community Demo"
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ## Gloo Edge Configuration
    ####
    # Gloo Edge Setup
    deploy_gloo_edge: true #<.>
    extra_port_mappings_offset: 2

  roles:
    - kameshsampath.kubernetes_spices.kind
    - kameshsampath.kubernetes_spices.k8s_app_spices
