---
- name: "Gloo Edge Enterprise Demo"
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    
    ## Gloo Edge Configuration
    ####
    # Gloo Edge Setup
    deploy_gloo_edge: true <.>
    # Enable/disable discovery true/false
    gloo_discovery_enabled: false <.>
    # Namespace to install Gloo into
    gloo_write_namespace: my-gloo <.>
    # Gloo Watch Namespaces
    gloo_watch_namespaces: <.>
      - demo-1-8-6
      - demo-1-10-2
      - my-gloo
    # Use NodePorts for Gloo Proxy http/https true/false
    gloo_proxy_nodeport: true <.>

  roles:
    - kameshsampath.kubernetes_spices.kind
    - kameshsampath.kubernetes_spices.k8s_app_spices
