---
- name: "Kind with Gloo Edge CE"
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    ####
    ## KinD cluster setup
    ####
    cluster_name: gloo-edge-ce
    # valid values are ipv4, ipv6, dual
    kind_ip_family: ipv4
    # Create Cluster
    kind_create: true
    # Destroy Cluster
    kind_destroy: false
    ####
    ## Gloo Edge Configuration
    ####
    # Gloo Edge Setup
    deploy_gloo_edge: true
    # deploy Gloo Edge Enterprise
    gloo_edge_edition: "ce"
    # Enable/disable discovery true/false
    gloo_discovery_enabled: false
    # Namespace to install Gloo into
    gloo_write_namespace: my-gloo
    # Gloo Watch Namespaces
    gloo_watch_namespaces:
      - demo-1-8-6
      - demo-1-10-2
      - my-gloo
      - gloo-system
    # Use NodePorts for Gloo Proxy http/https true/false
    gloo_proxy_nodeport: true

  roles:
    - kameshsampath.kubernetes_spices.kind
    - kameshsampath.kubernetes_spices.k8s_app_spices
