---
- name: vanilla
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core

  vars:
    cluster_name: vanilla
    kind_create: true

  roles:
    - role: kameshsampath.kubernetes_spices.kind
