---
# This runs only for clusters that are built and run locally
# e.g. KinD
- name: "Local Cloud"
  hosts: kind
  connection: local

  collections:
    - kubernetes.core
    - kameshsampath.kubernetes_spices
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    kind_create: true
    cluster_name: vanilla
  roles:
    - name: kameshsampath.kubernetes_spices.kind