---
- name: vanilla-2
  hosts: localhost
  connection: local

  collections:
    - kubernetes.core

  vars:
    cluster_name: vanilla-2
    kind_create: true
    extra_port_mappings_offset: 1

  roles:
    - role: kameshsampath.kubernetes_spices.kind
