galaxy_info:
  role_name: k8s_app_spices
  author: kameshsampath
  description: Ansible role to spice you Kubernetes cluster with components like Knative, Contour Ingress, Tektoncd etc.,

  license: 'license(Apache-2)'

  min_ansible_version: 2.9

  platforms:
    - name: EL
      versions:
      - all
    - name: Debian
      versions:
      - all
    - name: Ubuntu
      versions:
      - all

  galaxy_tags:
    - kubernetes
    - docker
    - knative
    - tekton
    - contour

dependencies: []
