---
- name: 'Wait for Deployment'
  kubernetes.core.k8s_info:
    kind: Deployment
    name: '{{ deployment_name }}'
    namespace: '{{ deployment_namespace }}'
    context: "{{ deployment_context }}"
  register: deployment_result
  until: ( deployment_result.resources[0].status.availableReplicas is defined) and (deployment_result.resources[0].status.availableReplicas == deployment_result.resources[0].status.replicas)
  retries: 18
  delay: 10