---
- name: "Add asdf-vm glooctl plugin"
  become: no
  ansible.builtin.shell: |
    source "{{ asdf_sh }}"
    asdf plugin-add glooctl https://github.com/kameshsampath/asdf-glooctl
    asdf install glooctl "{{ gloo_edge_version }}"
    asdf local glooctl "{{ gloo_edge_version }}"
    asdf reshim glooctl
  args:
    executable: /bin/bash
  changed_when: false

- name: "Ensure glooctl version is {{ gloo_edge_version }}"
  become: no
  ansible.builtin.shell: |
    source "{{ asdf_sh }}"
    asdf current glooctl | awk '{print $2}'
  args:
    executable: /bin/bash
  register: glooctl_version_result
  changed_when: false

- name: "Get glooctl installation path"
  become: no
  ansible.builtin.shell: |
    source "{{ asdf_sh }}"
    asdf where glooctl
  args:
    executable: /bin/bash
  register: glooctl_stat
  changed_when: false

#- debug:
#    var: glooctl_stat

- name: "Set glooctl Revision and Binary"
  become: no
  set_fact:
    glooctl_binary: "{{ glooctl_stat.stdout }}/bin/glooctl"

- name: "Ensure gloo write namespace is in gloo watch namespaces"
  set_fact:
    gloo_watch_namespaces: "{{ gloo_watch_namespaces + [ gloo_write_namespace ] }}"

#- debug:
#    var: gloo_watch_namespaces

- name: "Create temporary gloo install directory"
  ansible.builtin.tempfile:
    state: directory
    prefix: "{{ 'gloo_' + gloo_edge_edition + '_' }}"
  register: gloo_install_tmpdir

#- debug:
#    var: gloo_install_tmpdir

- name: "Create Gloo {{ gloo_edge_edition }} Helm Values"
  template:
    src: "gloo/{{ gloo_edge_edition }}/install-overrides.yaml.j2"
    dest: "{{ gloo_install_tmpdir.path }}/install-overrides.yaml"
  register: gloo_install_override_file

- name: Add File to gloo install overrides
  set_fact:
    gloo_install_override_files: "{{ gloo_install_override_files + [gloo_install_override_file.dest] }}"

#- set_fact:
#    temp_file: "{{ lookup('file',gloo_install_tmpdir.path +'/install-overrides.yaml') | from_yaml }}"

#- debug:
#    var: temp_file

################################################################################
## Gloo Edge community
################################################################################

- name: "Add Gloo Community chart repo"
  kubernetes.core.helm_repository:
    name: gloo
    repo_url: "https://storage.googleapis.com/solo-public-helm"
  when: gloo_edge_edition == 'ce'

- name: "Deploy Gloo Edge community v{{ gloo_edge_version }}"
  kubernetes.core.helm:
    chart_ref: "gloo/gloo"
    chart_version: "{{ gloo_edge_version }}"
    release_name: gloo
    release_namespace: "{{ gloo_write_namespace }}"
    values_files: "{{ gloo_install_override_files }}"
    create_namespace: true
    update_repo_cache: true
    wait: "{{ true and gloo_proxy_nodeport }}"
    wait_timeout: 5m
    context: "{{ k8s_current_context }}"
    kubeconfig: "{{ kubeconfig_file }}"
  when: gloo_edge_edition == 'ce'

################################################################################
## Gloo Edge Enterprise
################################################################################

- name: "Fail when enterprise license key is not provided"
  fail:
    msg: "No Enterprise License key provided"
  when: gloo_edge_edition == 'ee' and gloo_license_key is not defined

- name: "Add Gloo Edge enterprise chart repo"
  kubernetes.core.helm_repository:
    name: glooe
    repo_url: "https://storage.googleapis.com/gloo-ee-helm"
  when: gloo_edge_edition == 'ee'

  #- name: "Debug Install values"
  #  debug: msg="{{ lookup('template', 'gloo/' + gloo_edge_edition + '/install-overrides.yaml.j2') | from_yaml }}"
- name: "Deploy Gloo Enterprise v{{ gloo_edge_version }}"
  kubernetes.core.helm:
    context: "{{ k8s_current_context }}"
    kubeconfig: "{{ kubeconfig_file }}"
    release_name: gloo
    chart_ref: "glooe/gloo-ee"
    chart_version: "{{ gloo_edge_version }}"
    release_namespace: "{{ gloo_write_namespace }}"
    values_files: "{{ gloo_install_override_files }}"
    create_namespace: true
    update_repo_cache: true
    wait: "{{ true and gloo_proxy_nodeport }}"
  register: glooee_install
  when: gloo_edge_edition == 'ee'

  #- debug:
  #    var: glooee_install
- name: "Wait for Gloo Serving::discovery to be ready"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: discovery
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_discovery_enabled

- name: "Wait for Gloo Gateway::extauth to be ready"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: extauth
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

- name: "Wait for Gloo Gateway::gateway to be ready"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: gateway
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport

- name: "Wait for Gloo Serving::gateway-proxy to be ready"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: gateway-proxy
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport

- name: "Wait for Gloo Serving::gloo to be ready "
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: gloo
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport

- name: "Wait for Gloo Serving::gloo-fed to be ready"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: gloo-fed
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

- name: "Wait for Gloo Serving::gloo-fed-console to be ready "
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: gloo-fed-console
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

- name: "Wait for Gloo Serving::glooe-grafana to be ready "
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: glooe-grafana
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

- name: "Wait for Gloo Serving::glooe-prometheus-kube-state-metrics to be ready "
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: glooe-prometheus-kube-state-metrics
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

- name: "Wait for Gloo Serving::glooe-prometheus-server to be ready "
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: glooe-prometheus-server
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

- name: "Wait for Gloo Serving::observability to be ready "
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: observability
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

- name: "Wait for Gloo Serving::rate-limit to be ready "
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: rate-limit
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

- name: "Wait for Gloo Serving::redis to be ready "
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: redis
    deployment_namespace: "{{ gloo_write_namespace }}"
  when: not gloo_proxy_nodeport and gloo_edge_edition == 'ee'

################################################################################
## Deploy Knative Ingress
################################################################################

- name: "Configure Knative Networking with Gloo"
  ansible.builtin.command:
    args:
      - "{{ glooctl_binary }}"
      - install
      - knative
      - --install-knative=false
  when: deploy_knative
  changed_when: false
