---
- name: "Add ASDF istio plugin"
  become: no
  ansible.builtin.shell: |
    source "{{ asdf_sh }}"
    asdf plugin-add istio https://github.com/kameshsampath/asdf-istio
    asdf install istio "{{ istio_version }}"
    asdf local istio "{{ istio_version }}"
    asdf reshim istio
  args:
    executable: /bin/bash
  changed_when: false

- name: "Ensure istio version is {{ istio_version }}"
  become: no
  ansible.builtin.shell: |
    source "{{ asdf_sh }}"
    asdf current istio | awk '{print $2}'
  args:
    executable: /bin/bash
  register: istio_version_result
  changed_when: false

- name: "Get istio installation path"
  become: no
  ansible.builtin.shell: |
    source "{{ asdf_sh }}"
    asdf where istio
  args:
    executable: /bin/bash
  register: istio_stat
  changed_when: false
  
- name: "Set Istio Revision and Binary"
  become: no
  set_fact:
    istio_binary: "{{ istio_stat.stdout }}/bin/istioctl"
    istio_version: "{{ istio_version_result.stdout }}"
    istio_revision: "{{  istio_version_result.stdout | regex_replace('\\.','-')}}"

- name: "Create istio-system namespace"
  become: no
  kubernetes.core.k8s:
    name: "{{ istio_namespace }}"
    api_version: v1
    kind: Namespace
    state: present

- name: "Install istio Control Plane and Service {{ istio_version }}"
  become: no
  ansible.builtin.script: istio/installControlPlane.sh
  environment:
    ISTIO_NS: "{{ istio_namespace }}"
    ISTIO_VERSION: "{{ istio_version }}"
    ISTIO_REVISION: "{{ istio_revision }}"
    ISTIO_BINARY: "{{ istio_binary }}"
    ISTIO_NAMESPACE: "{{ istio_namespace }}"
    CONTROL_PLANE_MANIFEST: "{{ lookup('template','istio/istio-control-plane.yaml.j2') }}"
    ISTIOD_SERVICE_MANIFEST: "{{ lookup('template','istio/istiod-service.yaml.j2') }}"
  register: istio_install
  changed_when: false

#- name: "Debug Istio Install"
#  debug:
#    var: istio_install
    
- name: "Install istio Ingress Gateway"
  become: no
  ansible.builtin.script: istio/installGateway.sh
  environment:
    ISTIO_NS: "{{ istio_namespace }}"
    ISTIO_VERSION: "{{ istio_version }}"
    ISTIO_REVISION: "{{ istio_revision }}"
    ISTIO_BINARY: "{{ istio_binary }}"
    ISTIO_NAMESPACE: "{{ istio_namespace }}"
    ISTIO_GATEWAY_MANIFEST: "{{ lookup('template','istio/istio-ingress-gateway.yaml.j2') }}"
  register: istio_gw_install
  changed_when: false
  when: deploy_istio_gateway or not deploy_gloo_edgeipv
# - debug:
#    var: istio_gw_install

