---
- name: "Create Keycloak Namespace"
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ keycloak_namespace }}"
    state: present

- name: "Create Keycloak Service"
  kubernetes.core.k8s:
    template: keycloak/service.yaml.j2
    state: present
  register: keycloak_deploy

- name: "Deploy Keycloak"
  kubernetes.core.k8s:
    template: keycloak/deployment.yaml.j2
    state: present
  register: keycloak_deploy

- name: "Wait for Keycloak::deploy"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: keycloak
    deployment_namespace: "{{ keycloak_namespace }}"

- name: "Create Keycloak Demo Script Configmap"
  kubernetes.core.k8s:
    template: keycloak/int-job-cm.yaml.j2
    state: present
  register: keycloak_job

- name: "Setup Keycloak for Demos"
  kubernetes.core.k8s:
    template: keycloak/keycloak_init_job.yaml.j2
    state: present
    wait: true
  register: keycloak_job
  