---
- name: Get minikube IP
  command:
    argv:
      - minikube
      - -p
      - "{{ minikube_profile_name }}"
      - ip
  when:
    - k8s_cluster_ip is not defined
    - kubernetes_cluster_type == 'minikube'
  register: minikube_ip_result

- name: Set minikube IP as Kubernetes Cluster IP
  set_fact:
    k8s_cluster_ip: "{{ minikube_ip_result.stdout }}"
  when:
    - k8s_cluster_ip is not defined
    - kubernetes_cluster_type == 'minikube'

- name: Set Kubernetes Cluster IP for KinD
  set_fact:
    k8s_cluster_ip: "127.0.0.1"
  when:
    - kind_create | default(False)
    - k8s_cluster_ip is not defined

- name: "Install Tools"
  include: tools.yml

- name: "Setup Operator Lifecycle Manager(OLM)"
  include: olm.yml
  when: deploy_olm

## Handle default kubernetes context
- name: "Add Kubernetes Spices to Default Kubernetes Context"
  include: run_on_k8s_context.yml
