---
- name: Get minikube IP
  command:
    argv:
      - minikube
      - -p
      - "{{ minikube_profile_name }}"
      - ip
  when: k8s_cluster_ip is not defined and kubernetes_cluster_type == 'minikube'
  register: minikube_ip_result

- name: Set minikube IP as Kubernetes Cluster IP
  set_fact:
    k8s_cluster_ip: "{{ minikube_ip_result.stdout }}"
  when: k8s_cluster_ip is not defined and kubernetes_cluster_type == 'minikube'

- name: Set Kubernetes Cluster IP for KinD
  set_fact:
    k8s_cluster_ip: "127.0.0.1"
  when: k8s_cluster_ip is not defined and kubernetes_cluster_type == 'kind'

- name: "Install Tools"
  include: tools.yml

###################################
# Istio
###################################

- name: Istio
  ansible.builtin.include_tasks: istio.yml
  vars:
    istio_version: "{{ item }}"
  when: deploy_istio
  loop: "{{ istio_versions | list }}"

###################################
# Gloo Edge
###################################
- name: "Deploy Gloo Edge"
  include_tasks: gloo_edge.yml
  when: deploy_gloo_edge

######################################
## Knative Serving and Eventing
######################################
- name: Deploy Knative Serving and Eventing
  include_tasks: knative.yml
  when: deploy_knative

###################################
# Tektoncd
###################################

- name: Deploy Tektoncd Pipelines and Triggers
  include_tasks: tektoncd.yml
  when: deploy_tektoncd
