---
- name: Get minikube IP
  command:
    argv:
      - minikube
      - -p
      - "{{ minikube_profile_name }}"
      - ip
  when: k8s_cluster_ip is not defined and kubernetes_cluster_type == 'minikube'
  register: minikube_ip_result

- name: Set minikube IP as Kubernetes Cluster IP
  set_fact:
    k8s_cluster_ip: "{{ minikube_ip_result.stdout }}"
  when: k8s_cluster_ip is not defined and kubernetes_cluster_type == 'minikube'

- name: Set Kubernetes Cluster IP for KinD
  set_fact:
    k8s_cluster_ip: "127.0.0.1"
  when: k8s_cluster_ip is not defined and kubernetes_cluster_type == 'kind'

- name: "Install Tools"
  include: tools.yml

## Handling multiple kubernetes contexts
- name: "Add Kubernetes Spices"
  include: run_on_k8s_context.yml
  vars:
    k8s_use_context: "{{ k8s_context_item }}"
  loop: "{{ k8s_contexts }}"
  loop_control:
    loop_var: k8s_context_item
  when: k8s_contexts is defined

## Handle default kubernetes context
- name: "Add Kubernetes Spices to Default Kubernetes Context"
  include: run_on_k8s_context.yml
  when: k8s_contexts is defined or kind_create
