---
- name: "Create Postgresql Namespace"
  kubernetes.core.k8s:
    context: "{{ k8s_current_context }}"
    kubeconfig: "{{ kubeconfig_file }}"
    kind: Namespace
    api_version: v1
    name: "{{ postgresql_namespace }}"
    state: present

- name: "Create Postgresql PVC"
  kubernetes.core.k8s:
    context: "{{ k8s_current_context }}"
    kubeconfig: "{{ kubeconfig_file }}"
    template: postgresql/pvc.yaml.j2
    state: present
  register: keycloak_pvc_create
    
- name: "Create Postgresql Secret"
  kubernetes.core.k8s:
    context: "{{ k8s_current_context }}"
    kubeconfig: "{{ kubeconfig_file }}"
    template: postgresql/pgsql-credentials.yaml.j2
    state: present
  register: keycloak_secret_create
  
- name: "Create Postgresql Service"
  kubernetes.core.k8s:
    context: "{{ k8s_current_context }}"
    kubeconfig: "{{ kubeconfig_file }}"
    template: postgresql/service.yaml.j2
    state: present
  register: keycloak_deploy
  
- name: "Deploy Postgresql"
  kubernetes.core.k8s:
    context: "{{ k8s_current_context }}"
    kubeconfig: "{{ kubeconfig_file }}"
    template: postgresql/deployment.yaml.j2
    state: present
  register: keycloak_deploy

- name: "Wait for Postgresql::deploy"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: postgresql
    deployment_namespace: "{{ postgresql_namespace }}"