###################################
# Istio
###################################

- name: Istio
  ansible.builtin.include_tasks: istio.yml
  vars:
    istio_version: "{{ istio_version_item }}"
  when: deploy_istio
  loop: "{{ istio_versions }}"
  loop_control:
    loop_var: istio_version_item

###################################
# Gloo Edge
###################################
- name: "Deploy Gloo Edge"
  include_tasks: gloo_edge.yml
  when: deploy_gloo_edge

- name: "Undeploy Gloo Edge"
  include_tasks: rollback/gloo_edge.yml
  when: rollback_gloo_edge

######################################
## Keycloak
######################################
- name: Deploy Keycloak
  include_tasks: keycloak.yml
  when: deploy_keycloak

######################################
## Knative Serving and Eventing
######################################
- name: Deploy Knative Serving and Eventing
  include_tasks: knative.yml
  when: deploy_knative
  
######################################
## Postgresql Database
######################################
- name: Deploy Postgresql Database
  include_tasks: postgresql.yml
  when: deploy_postgresql
  
###################################
# Tektoncd
###################################

- name: Deploy Tektoncd Pipelines and Triggers
  include_tasks: tektoncd.yml
  when: deploy_tektoncd
