###################################
# Change Kube Context
###################################
- name: "Running on Kubernetes Context"
  debug: msg="Running on Kubernetes Context:{{ k8s_use_context }}"
  when: k8s_use_context is defined
  
- name: "Change kube context"
  ansible.builtin.command:
    argv:
      - kubectl
      - config 
      - set-context 
      - "{{ k8s_use_context }}"
  when: k8s_use_context is defined

###################################
# Istio
###################################

- name: Istio
  ansible.builtin.include_tasks: istio.yml
  vars:
    istio_version: "{{ istio_version_item }}"
  when: deploy_istio
  loop: "{{ istio_versions }}"
  loop_control:
    loop_var: istio_version_item

###################################
# Gloo Edge
###################################
- name: "Deploy Gloo Edge"
  include_tasks: gloo_edge.yml
  when: deploy_gloo_edge

######################################
## Knative Serving and Eventing
######################################
- name: Deploy Knative Serving and Eventing
  include_tasks: knative.yml
  when: deploy_knative

###################################
# Tektoncd
###################################

- name: Deploy Tektoncd Pipelines and Triggers
  include_tasks: tektoncd.yml
  when: deploy_tektoncd
