- name: Set Tektoncd manifest dir
  set_fact:
    tektoncd_manifests_dir: "/tmp/tektoncd"

- name: Force Deployment of Ingress
  set_fact:
    deploy_ingress: True
  when: not deploy_ingress

- name: Make temp directory for Tektoncd Manifests
  file:
    path: "{{ tektoncd_manifests_dir }}"
    state: directory

- name: Get Tektoncd Manifests
  get_url:
    dest: "{{ tektoncd_manifests_dir }}/{{ item.name }}"
    url: "{{ item.manifest_url }}"
  delegate_to: localhost
  loop:
    - name: pipelines.yaml
      manifest_url: "https://storage.googleapis.com/tekton-releases/pipeline/previous/{{ tektoncd_pipelines_version }}/release.yaml"
    - name: triggers.yaml
      manifest_url: "https://github.com/tektoncd/triggers/releases/download/{{ tektoncd_triggers_version }}/release.yaml"
  loop_control:
     label: "{{ item.name }}"

- name: Deploy Tektoncd Pipelines and Triggers
  community.kubernetes.k8s:
    definition: "{{ item.manifest | from_yaml_all | list }}"
    state: present
  loop:
    - name: pipelines.yaml
      manifest: "{{ lookup('file',tektoncd_manifests_dir + '/pipelines.yaml') }}"
    - name: triggers.yaml
      manifest: "{{ lookup('file',tektoncd_manifests_dir + '/triggers.yaml') }}"
  loop_control:
      label: "{{ item.name }}"
  changed_when: False
  register: tektoncd_deploy

- name: "Wait for Tektoncd Pipelines::controller"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: tekton-pipelines-controller
    deployment_namespace: tekton-pipelines

- name: "Wait for Tektoncd Pipelines::webhook"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: tekton-pipelines-webhook
    deployment_namespace: tekton-pipelines

- name: "Wait for Tektoncd Triggers::controller"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: tekton-triggers-controller
    deployment_namespace: tekton-pipelines

- name: "Wait for Tektoncd Triggers::webhook"
  include_tasks: utils/k8s_deployment_status.yml
  vars:
    deployment_name: tekton-triggers-webhook
    deployment_namespace: tekton-pipelines
