- name: "Add kubectl repository"
  become: yes
  yum_repository:
    name: Kubernetes
    description: Kubernetes YUM repo
    enabled: true
    gpgcheck: true
    repo_gpgcheck: true
    gpgkey: "https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"
    baseurl: "https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64"
