---
- name: Destroy 'deploy_tektoncd' test resources
  hosts: localhost
  connection: local

  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    minikube_profile_name: molecule-tektoncd
    minikube_destroy: True

  roles:
    - kameshsampath.minikube
