---
- name: Verify
  hosts: localhost
  connection: local

  collections:
  - community.kubernetes

  vars:
   ansible_python_interpreter: '{{ ansible_playbook_python }}'
   minikube_profile_name: molecule-tektoncd
   deploy_tektoncd: True
   deploy_ingress: True
   ingress_namespace: contour-system

  tasks:

   - import_tasks: ../common/tasks/ingress_verify.yml

   - name: Create Test namespace
     community.kubernetes.k8s:
      definition:
        kind: Namespace
        metadata:
          name: molecule-tekton-test
      state: present

   - import_tasks: tekton_verify.yml

- name: Destroy test resources
  import_playbook: destroy.yml
